SELECT  [TimeTrack].[Id]
      ,[TimeTrack].[ListTasksId]
      ,[TimeTrack].[StartDate]
      ,[TimeTrack].[EndDate]
      ,[TimeTrack].[Note]
      ,[TimeTrack].[StatusId]
      ,[TimeTrackStatus].[Name] as [StatusName]
      ,[TimeTrack].[IsBusinessTime]
      ,[TimeTrack].[JiraTaskCode]
      ,[TimeTrack].[CreatedAt]
      ,[TimeTrack].[CreatedUserById]
      ,[TimeTrack].[EditedAt]
      ,[TimeTrack].[EditedUserById]
  FROM [dbo].[TimeTrack]
  inner join [dbo].[TimeTrackStatus] on [TimeTrackStatus].[Id] = [TimeTrack].[StatusId]
where [TimeTrack].[Id] = @Id